development:
  adapter: postgresql
  encoding: unicode
  database: chitter
  pool: 2
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: chitter_test
  pool: 2
  username:
  password:
